export type ISODateString = string // YYYY-MM-DD
export type ISODateTimeString = string // YYYY-MM-DDThh:mm:ss±hh:mm
export type TaskIdentifier = string
export type ResourceIdentifier = string
export type ScheduleRuleString = string
export type Probability = number // 0 < Probability < 1
export type Percentage = number // 0 < Percentage < 1
export type Accuracy = number
export type Hours = number